# docker-compose.yml (已修正)
# 定义服务
services:
  # 服务的名称
  smoke-fire-hailo-service:
    # 构建指令
    build:
      # 'context'：构建上下文的路径。'.' 表示当前目录（即项目根目录）。
      context: .
      # 'dockerfile'：Dockerfile 的文件名，相对于 context。
      dockerfile: Dockerfile

    # 容器名称
    container_name: smoke_fire_hailo_service

    ports:
      - "${SERVER__PORT}:${SERVER__PORT}" # FastAPI
      - "${WEBUI__PORT}:${WEBUI__PORT}" # Streamlit

    volumes:
      - /dev:/dev
      - /lib/firmware:/lib/firmware
      - /lib/udev/rules.d:/lib/udev/rules.d
      - /lib/modules:/lib/modules
    devices:
      - /dev/hailo0:/dev/hailo0
    privileged: true
    environment:
      - HOST__IP=${HOST__IP}
      - SERVER__PORT=${SERVER__PORT}


    # 重启策略: 除非手动停止，否则容器总是在退出后重启
    restart: unless-stopped